### ISSUE TITLE
filters per channel?

### ISSUE THREAD

**Issue by gixxy22** [nilsenpaul/craft-easy-search#11]
hi, is it currently possible to create custom filters in the config on a per channel basis? I can only seem to add custom filters for all Entries, if I have multiple channels, some fields are not in the channel but will still show the custom filter which wouldnt make any sense to the user.

thanks

**Comment by nilsenpaul** [comment]
As of version 1.0.3 (just tagged a release), you can limit predefined queries to a certain element `source`, from within your config:

```
return [
  'queries' => [
    [
      'query' => 'title:*',
      'label' => 'All entries with a title',
      'element' => 'craft\\elements\\Entry',
      'source' => 'section:3ae083f5-a8c8-4506-b0cb-3f6469bd254d',
    ],
  ]
];
```

In case of entry sections, the source can be configured by prepending the unique ID of a section with `section:`. This would be `group:` in case of categories, and `folder:` in case of assets.

The UID for an element source can be obtained from the database (the `sections` table's `uid` column, in case of entry sections).
