### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by zawilliams** [nilsenpaul/craft-easy-search#13]
Hey hey!

Any chance this will be updated for Craft 4? Would like to upgrade but this is one of the last plugins I'm using that is blocking updates. Thanks!

**Comment by gixxy22** [comment]
Hi, also requiring this too.

Thanks

**Comment by zawilliams** [comment]
Checking in again on this. Is this plugin abandoned/should I look for another plugin to replace this?

**Comment by nilsenpaul** [comment]
Sorry for this, somehow we’ve completely missed this … we’ll take this up next week, find out what it takes to upgrade to Craft 4 and release an update ASAP.

**Comment by zawilliams** [comment]
Hey @nilsenpaul - no worries! Thanks for getting back to us! Looking forward to an update.

**Comment by nilsenpaul** [comment]
Hi all. After careful consideration, we decided to NOT release a Craft 4 version of this plugin. We believe that, with some enhancement, the element index filtering option added in Craft 4, in addition to having the ability to apply filtering to custom element indexes, makes our plugin obsolete.
