### ISSUE TITLE
Only field options are title and slug

### ISSUE THREAD

**Issue by benjaminkohl** [nilsenpaul/craft-easy-search#4]
I am testing this plugin locally to see if it will be a viable option for assisting our client in filtering entries in the control panel. We are using v1.0.0.1 in Craft v3.4.9 and so far I only see _title_ and _slug_ as field options across every channel. Where do I configure which fields show in the dropdown?

Ideally, we are looking to filter entries by particular relationships but it isn't something we can create pre-defined filters for in the config file because there are so many possible entry relationships that can exist and new entries are imported all the time.

**Comment by benjaminkohl** [comment]
I did some digging in the code and it looks like the field has to be searchable in order for it to show up as an option. We usually disable that option on fields just to minimize the size of the searchindex table. I'll just enable it for the fields we are concerned with.

**Comment by nilsenpaul** [comment]
@benjaminkohl the field has to be searchable, because what this plugin does is create a search query using the dropdown UI (or let users select a predefined one). As search queries don't work if fields are not searchable, being searchable is indeed a prerequisite for a (custom) field to appear in the dropdown.

**Comment by benjaminkohl** [comment]
Ah, that makes sense and it explains why it can tie into the existing element indexes so well. We built a separate filter module that uses the standard criteria syntax rather than the search syntax but it lives on its own page outside the standard element indexes.
