### ISSUE TITLE
Any plans for supporting Commerce order elements?

### ISSUE THREAD

**Issue by jalendport** [nilsenpaul/craft-easy-search#5]

**Comment by nilsenpaul** [comment]
@jalendport We've just added the default Commerce Order fields to the plugin, so you should now be able to search for both an order's 'default' searchable fields, in addition to the custom fields for orders:

![afbeelding](https://user-images.githubusercontent.com/6794819/110641431-4bc07d00-81b2-11eb-9b29-1e678f8140c0.png)
