### ISSUE TITLE
BUG: Some fields showing up multiple times in dropdown

### ISSUE THREAD

**Issue by adrienne** [nilsenpaul/craft-easy-search#8]
I think this is actually related to Entry Types: we have one section that has multiple Entry Types with overlapping fields, and somehow the same field is getting picked up multiple times if it is on the layout for multiple Entry Types. See screenshot:

![image](https://user-images.githubusercontent.com/89705/115156771-c2b32600-a03a-11eb-8d6b-2b6e337c0eab.png)

The "duplicate" fields in that list are all actually the same field.

**Comment by nilsenpaul** [comment]
Will look into this!

**Comment by adrienne** [comment]
@nilsenpaul -- thanks. If you need me to help test, i can absolutely help anytime. I would like this fixed asap because it's going to drive my client nuts in production.

**Comment by nilsenpaul** [comment]
Fixed this with v1.0.2
