### ISSUE TITLE
FR: Fix enter key behavior and possibly add button

### ISSUE THREAD

**Issue by adrienne** [nilsenpaul/craft-easy-search#9]
(one more, sorry!) 

Currently, when building a query, hitting the Enter key inside a text field triggers the "Add Another Condition" button, which is pretty confusing and also makes it really non-intuitive about how you should actually submit the query you've built.

I suggest that you:
- Add a "Search" button to the dialog
- and make it the primary button (so if you hit Enter, it triggers _that_ instead of the Add A Condition
![image](https://user-images.githubusercontent.com/89705/115440275-6aa82b00-a1c4-11eb-82ed-08eca97c2c40.png)

**Comment by nilsenpaul** [comment]
Just tagged v1.0.2, which adds a 'submit button' and handles an [enter] event on inputs by closing the search hud, thus showing the results.

**Comment by adrienne** [comment]
Thank you, @nilsenpaul!
